# Generated by Django 5.2.12 on 2026-04-06 00:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matches', '0001_initial'),
        ('teams', '0001_initial'),
        ('tournaments', '0002_alter_field_availability'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('match_started', 'Match démarré'), ('match_finished', 'Match terminé'), ('score_updated', 'Score mis à jour'), ('planning_generated', 'Planning généré'), ('field_change', 'Changement de terrain'), ('tournament_published', 'Tournoi publié')], max_length=30)),
                ('target', models.CharField(choices=[('admin', 'Admin'), ('coach', 'Coach'), ('all', 'Tous')], default='all', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True, default='')),
                ('link', models.CharField(blank=True, default='', max_length=500)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='matches.match')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='teams.team')),
                ('tournament', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='tournaments.tournament')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='notificatio_created_ae6ed6_idx'), models.Index(fields=['tournament', 'target', '-created_at'], name='notificatio_tournam_5782e3_idx')],
            },
        ),
    ]
