# Generated by Django 5.2.3 on 2026-04-05 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('short_name', models.CharField(blank=True, help_text='Pour affichage mobile', max_length=20)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='teams/')),
                ('coach_name', models.CharField(blank=True, max_length=200)),
                ('coach_phone', models.CharField(blank=True, max_length=20)),
                ('coach_email', models.EmailField(blank=True, max_length=254)),
                ('access_code', models.CharField(db_index=True, max_length=8, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='tournaments.category')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='tournaments.tournament')),
            ],
            options={
                'ordering': ['category', 'name'],
                'unique_together': {('tournament', 'category', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='tournaments.category')),
                ('teams', models.ManyToManyField(blank=True, related_name='groups', to='teams.team')),
            ],
            options={
                'ordering': ['category', 'display_order'],
                'unique_together': {('category', 'name')},
            },
        ),
    ]
