# Generated by Django 5.2.15 on 2026-08-07 15:09

import apps.core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teams", "0002_team_token_version"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="logo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="teams/",
                validators=[
                    django.core.validators.FileExtensionValidator(["png", "jpg", "jpeg", "webp"]),
                    apps.core.validators.validate_image_size,
                ],
            ),
        ),
    ]
