# Generated by Django 5.2.12 on 2026-04-06 21:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
        ('tournaments', '0004_add_public_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.CharField(choices=[('free', 'Gratuit'), ('monthly', 'Mensuel'), ('yearly', 'Annuel'), ('club_monthly', 'Club Mensuel'), ('club_yearly', 'Club Annuel')], default='free', max_length=20),
        ),
        migrations.CreateModel(
            name='TournamentLicense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stripe_customer_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('stripe_payment_intent_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('stripe_checkout_session_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tournament', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='license', to='tournaments.tournament')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_licenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'subscriptions_tournamentlicense',
            },
        ),
    ]
