# Generated by Django 5.2.3 on 2026-04-07 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_pricing_v2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentlicense',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
