# Generated by Django 5.2.3 on 2026-04-07 14:49

from django.db import migrations, models


def deactivate_unpaid_licenses(apps, schema_editor):
    """Deactivate licenses that were created active but never paid for."""
    TournamentLicense = apps.get_model("subscriptions", "TournamentLicense")
    TournamentLicense.objects.filter(
        is_active=True,
        stripe_payment_intent_id="",
    ).update(is_active=False)


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_license_active_default_true'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentlicense',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(
            deactivate_unpaid_licenses,
            migrations.RunPython.noop,
        ),
    ]
