# Generated by Django 5.2.3 on 2026-04-05 12:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
        ('tournaments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phase', models.CharField(choices=[('group', 'Phase de poules'), ('r16', '8èmes de finale'), ('quarter', 'Quart de finale'), ('semi', 'Demi-finale'), ('third', 'Petite finale'), ('final', 'Finale')], default='group', max_length=20)),
                ('placeholder_home', models.CharField(blank=True, help_text="ex: '1er Poule A'", max_length=100)),
                ('placeholder_away', models.CharField(blank=True, max_length=100)),
                ('start_time', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField(default=15)),
                ('status', models.CharField(choices=[('scheduled', 'Programmé'), ('live', 'En direct'), ('finished', 'Terminé'), ('cancelled', 'Annulé'), ('postponed', 'Reporté')], default='scheduled', max_length=20)),
                ('score_home', models.PositiveIntegerField(blank=True, null=True)),
                ('score_away', models.PositiveIntegerField(blank=True, null=True)),
                ('score_validated', models.BooleanField(default=False)),
                ('is_locked', models.BooleanField(default=False, help_text="Si True, le moteur ne touche pas à ce match lors d'un recalcul")),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='tournaments.category')),
                ('field', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='tournaments.field')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='teams.group')),
                ('score_entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('team_away', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='teams.team')),
                ('team_home', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='teams.team')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='tournaments.tournament')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(blank=True, max_length=200)),
                ('minute', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='matches.match')),
            ],
            options={
                'ordering': ['minute', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['tournament', 'start_time'], name='matches_mat_tournam_28b0dd_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['field', 'start_time'], name='matches_mat_field_i_deb664_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['status'], name='matches_mat_status_a896a5_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['category', 'phase'], name='matches_mat_categor_41dcf0_idx'),
        ),
    ]
