# Generated by Django 5.2.12 on 2026-04-06 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='penalty_score_away',
            field=models.PositiveIntegerField(blank=True, help_text='Tirs au but extérieur (phases finales uniquement)', null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='penalty_score_home',
            field=models.PositiveIntegerField(blank=True, help_text='Tirs au but domicile (phases finales uniquement)', null=True),
        ),
    ]
