# Generated by Django 5.2.3 on 2026-04-09 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_add_penalty_scores'),
        ('tournaments', '0005_category_finals_format_category_finals_same_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='tournaments.day'),
        ),
        migrations.AddField(
            model_name='match',
            name='slot_index',
            field=models.IntegerField(blank=True, help_text='Index du créneau global (pour tri chronologique)', null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='source_away',
            field=models.ForeignKey(blank=True, help_text="Match source pour l'équipe extérieur", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_away_matches', to='matches.match'),
        ),
        migrations.AddField(
            model_name='match',
            name='source_away_type',
            field=models.CharField(blank=True, help_text="'winner' ou 'loser' du match source_away", max_length=10),
        ),
        migrations.AddField(
            model_name='match',
            name='source_home',
            field=models.ForeignKey(blank=True, help_text="Match source pour l'équipe domicile (ex: demi-finale)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_home_matches', to='matches.match'),
        ),
        migrations.AddField(
            model_name='match',
            name='source_home_type',
            field=models.CharField(blank=True, help_text="'winner' ou 'loser' du match source_home", max_length=10),
        ),
    ]
