# Generated by Django 5.2.3 on 2026-04-05 12:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('location', models.CharField(max_length=300)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('rules', models.TextField(blank=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='tournaments/')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publié'), ('live', 'En cours'), ('finished', 'Terminé'), ('archived', 'Archivé')], default='draft', max_length=20)),
                ('is_public', models.BooleanField(default=True)),
                ('default_match_duration', models.PositiveIntegerField(default=15, help_text="Durée d'un match en minutes")),
                ('default_transition_time', models.PositiveIntegerField(default=5, help_text='Temps de transition entre deux matchs en minutes')),
                ('default_rest_time', models.PositiveIntegerField(default=20, help_text="Repos minimum entre deux matchs d'une même équipe en minutes")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournaments', to='clubs.club')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='SchedulingConstraint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('constraint_type', models.CharField(choices=[('earliest_time', 'Heure minimum'), ('latest_time', 'Heure maximum'), ('required_field', 'Terrain imposé'), ('blocked_slot', 'Créneau bloqué'), ('category_day', 'Catégorie sur jour précis')], max_length=30)),
                ('payload', models.JSONField(help_text='Structure dépend du type. Voir SCHEDULING_ENGINE_SPEC.md')),
                ('is_hard', models.BooleanField(default=True, help_text='True = contrainte obligatoire, False = préférence')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constraints', to='tournaments.tournament')),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('availability', models.JSONField(default=list)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='tournaments.tournament')),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('color', models.CharField(default='#3b82f6', max_length=7)),
                ('match_duration', models.PositiveIntegerField(blank=True, null=True)),
                ('transition_time', models.PositiveIntegerField(blank=True, null=True)),
                ('rest_time', models.PositiveIntegerField(blank=True, null=True)),
                ('players_per_team', models.PositiveIntegerField(default=7)),
                ('points_win', models.PositiveIntegerField(default=3)),
                ('points_draw', models.PositiveIntegerField(default=1)),
                ('points_loss', models.PositiveIntegerField(default=0)),
                ('allowed_days', models.JSONField(blank=True, default=list, help_text='Liste de dates ISO où cette catégorie peut jouer. Vide = toutes.')),
                ('earliest_start', models.TimeField(blank=True, null=True)),
                ('latest_end', models.TimeField(blank=True, null=True)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='tournaments.tournament')),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AddIndex(
            model_name='tournament',
            index=models.Index(fields=['club', 'status'], name='tournaments_club_id_7d6885_idx'),
        ),
        migrations.AddIndex(
            model_name='tournament',
            index=models.Index(fields=['slug'], name='tournaments_slug_2e3c0a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='field',
            unique_together={('tournament', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('tournament', 'name')},
        ),
    ]
