# Generated by Django 5.2.3 on 2026-04-05 13:31

import apps.tournaments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='availability',
            field=models.JSONField(default=list, validators=[apps.tournaments.models.validate_availability]),
        ),
    ]
