# Generated by Django 5.2.12 on 2026-04-06 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_alter_field_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='knockout_rest_multiplier',
            field=models.PositiveIntegerField(default=3, help_text='Multiplicateur de repos entre dernière poule et première phase finale'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='phase_separation_mode',
            field=models.CharField(choices=[('none', "Aucune séparation — tout dans l'ordre naturel"), ('same_day_rest', 'Même jour avec repos minimum augmenté'), ('next_day', 'Phases finales au jour suivant')], default='same_day_rest', help_text='Comment séparer les phases de poules des phases finales', max_length=20),
        ),
    ]
