# Generated by Django 5.2.12 on 2026-04-06 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
        ('tournaments', '0003_add_phase_separation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedulingconstraint',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='tournament',
            name='public_code',
            field=models.CharField(blank=True, help_text="Code unique à 6 caractères pour l'accès spectateur", max_length=6, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='tournament',
            index=models.Index(fields=['public_code'], name='tournaments_public__cda94c_idx'),
        ),
    ]
