# Generated by Django 5.2.3 on 2026-04-09 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0004_add_public_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='finals_format',
            field=models.CharField(choices=[('TOP2_CROSSOVER', '1er vs 2e croisé (demi-finales)'), ('TOP1_FINAL', '1er de chaque poule en finale directe')], default='TOP2_CROSSOVER', max_length=20),
        ),
        migrations.AddField(
            model_name='category',
            name='finals_same_day',
            field=models.BooleanField(default=True, help_text='Si True, les finales sont le même jour que les poules'),
        ),
        migrations.AddField(
            model_name='category',
            name='max_consecutive_matches',
            field=models.PositiveIntegerField(blank=True, help_text='Nombre maximum de matchs consécutifs (surcharge tournoi)', null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='min_rest_matches',
            field=models.PositiveIntegerField(blank=True, help_text='Nombre minimum de créneaux de repos (surcharge tournoi)', null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='number_of_pools',
            field=models.PositiveIntegerField(blank=True, help_text="Nombre de poules souhaité pour l'auto-génération", null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='default_min_rest_matches',
            field=models.PositiveIntegerField(default=1, help_text="Nombre minimum de créneaux de repos entre deux matchs d'une même équipe"),
        ),
        migrations.AddField(
            model_name='tournament',
            name='max_consecutive_matches',
            field=models.PositiveIntegerField(default=2, help_text='Nombre maximum de matchs consécutifs pour une équipe'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='scheduling_mode',
            field=models.CharField(choices=[('CATEGORY_BLOCK', "Par catégorie (une catégorie après l'autre)"), ('INTERLEAVE', 'Entrelacé (matchs de toutes catégories mélangés)')], default='CATEGORY_BLOCK', max_length=20),
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('label', models.CharField(blank=True, max_length=100)),
                ('start_time', models.CharField(default='08:30', help_text='Heure de début (HH:MM)', max_length=5)),
                ('end_time', models.CharField(default='17:30', help_text='Heure de fin (HH:MM)', max_length=5)),
                ('lunch_start', models.CharField(blank=True, default='12:00', help_text='Début pause déjeuner (HH:MM)', max_length=5)),
                ('lunch_end', models.CharField(blank=True, default='13:00', help_text='Fin pause déjeuner (HH:MM)', max_length=5)),
                ('order', models.PositiveIntegerField(default=0)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='tournaments.tournament')),
            ],
            options={
                'ordering': ['order', 'date'],
                'unique_together': {('tournament', 'date')},
            },
        ),
        migrations.AddField(
            model_name='category',
            name='day',
            field=models.ForeignKey(blank=True, help_text='Jour assigné à cette catégorie (vide = répartition auto)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='tournaments.day'),
        ),
    ]
