# Generated by Django 5.2.15 on 2026-08-07 15:09

import apps.core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tournaments", "0005_category_finals_format_category_finals_same_day_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tournament",
            name="cover_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="tournaments/",
                validators=[
                    django.core.validators.FileExtensionValidator(["png", "jpg", "jpeg", "webp"]),
                    apps.core.validators.validate_image_size,
                ],
            ),
        ),
    ]
